#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Nov 14 12:25:28 GMT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=false
